sonar.projectKey=mi-proyecto-gestion-sw
sonar.projectName=Sistema Registro Universitario

# Fuentes a analizar
sonar.sources=.
sonar.tests=tests

# Exclusiones
sonar.exclusions=node_modules/**,coverage/**,*.json,*.md

# Reporte de cobertura generado por Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
